# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171013_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=20)),
                ('post_content', models.CharField(max_length=200)),
                ('post_img', models.ImageField(default='home/img/ecoctil_5.jpg', upload_to='home/img/')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
