# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclama_title', models.CharField(max_length=20)),
                ('reclama_content', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'reclama',
            },
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=models.TextField(max_length=200),
        ),
    ]
