# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171014_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_two',
            name='article',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='article',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='article',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_img',
            field=models.ImageField(upload_to='home/img'),
        ),
    ]
