# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_emeil',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
    ]
