# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='call_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Тел.'),
        ),
    ]
