# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='count',
            new_name='namber',
        ),
    ]
