# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_price_namber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='namber',
        ),
        migrations.AddField(
            model_name='price',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
