# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0007_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('price_text', models.TextField(blank=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('threshold2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price',
            },
        ),
    ]
