# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('cummary', models.TextField(blank=True, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_modified', models.DateTimeField(auto_now_add=True)),
                ('is_cover_photo', models.BooleanField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Album')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
