# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_cover_photo',
        ),
    ]
