# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_photo_is_cover_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
    ]
