# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20171015_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='cummary',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='data_created',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='data_modified',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
