# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20171016_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
