# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(blank=True, max_length=200)),
                ('album_text', models.TextField(blank=True, max_length=500)),
                ('сonnection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Photo')),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
