# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='сonnection',
        ),
        migrations.AddField(
            model_name='album',
            name='connection',
            field=models.ManyToManyField(to='portfolio.Photo'),
        ),
    ]
