# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20171016_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='connection',
        ),
        migrations.AddField(
            model_name='album',
            name='connection',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Photo'),
            preserve_default=False,
        ),
    ]
