# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20171017_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='connection',
        ),
        migrations.AddField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Album'),
            preserve_default=False,
        ),
    ]
