# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20171015_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(blank=True, upload_to='home/img'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_test',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
