# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20171015_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Про тебе'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about_test',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Стаття'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
    ]
